### ISSUE TITLE
unsupported nexus format

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/phyltr#16]
Currently, `phyltr cat` fails to parse the trees in [this nexus file](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/grollemund_et_al2015/posterior.trees), which lists trees using the following syntax:
```
	tree tree.556080000.61430.650391 = ((((51:1053.9639237131@0.8337259884,((49:242.4904568448@0.9159863592,50:242.4904568448@1.5390144529):204.6990743163@1.1320055657,48:447.1895311610@1.6129497417):606.7743925520@0.3544631032):321.7288454256@0.8110941854,
```
right in the `translate block!

Dunno whether this is proper nexus format at all.

**Comment by lmaurits** [comment]
"Proper nexus format" is, unfortunately, a bit of a mythical entity, because so many different biological software packages have added their own idiosyncratic extensions.

I've never seen the use of `@` in a nexus file before, but I would guess that what's happening here is something like `branchlength@relativeclockrate`.  There is actually a "standard" way to add this kind of additional metadata to branches, which is understood by ETE and hence Phyltr.

In keeping with Postel's law, I would suggest:

1. Fixing phyltr to handle this variant since we've seen it in the wild
2. D-PLACE adopting a single, explicit standard format for its trees and a policy of converting all 3rd party trees to that format

**Comment by xrotwang** [comment]
Agree with both. And I didn't even realize, there was a `@` in there :)

**Comment by xrotwang** [comment]
So I guess that's going to be another regex in the `get_tree` function, right? Should I have a go?

**Comment by lmaurits** [comment]
Yeah, I guess so, with a new replacement function which puts the branch rates into the `[&&NHX:]` function.  I guess with the name `rate`?  Feel free to have a try, otherwise I can probably take a shot this evening.

**Comment by xrotwang** [comment]
ok. Can I implement this on top of the other changes in my current PR?

**Comment by lmaurits** [comment]
No, because I just merged it :p

**Comment by SimonGreenhill** [comment]
Yeah that's weird. I'd be in favor of dplace's import culling this and saving the fixed versions in 'posterior.trees' as there'll be other programs that can't handle this in the current format (and DPLACE is the entry point for these into our ecosystem).

**Comment by xrotwang** [comment]
@SimonGreenhill yes, but if we make `phyltr` handle this, we can use `phyltr` as import helper for D-PLACE :)
